//
//  Style Guide v7.2
//  
//  Automatically generated by StyleSync
//  https://github.com/dylanslewis/StyleSync
//

import UIKit

extension UIColor {

	public static let sampleBlack = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)

	public static let sampleGreen = UIColor(red: 0.135341621721612, green: 0.536033163265306, blue: 0.0275694139960672, alpha: 1.0)

	public static let sampleFire = UIColor(red: 0.872395833333333, green: 0.287587669675442, blue: 0.0456610271826336, alpha: 1.0)

	public static let sampleRed = UIColor(red: 0.830064838435374, green: 0.181101780465925, blue: 0.260694606556433, alpha: 1.0)

	public static let allGeneratedStylesAndCodeNameAndName: [(UIColor, String, String)] = [
		(.sampleBlack, "sampleBlack", "Sample Black"),
		(.sampleGreen, "sampleGreen", "Sample Green"),
		(.sampleFire, "sampleFire", "Sample Fire"),
		(.sampleRed, "sampleRed", "Sample Red"),
	]
}
