//
//  Style Guide v8.3
//  
//  Generated by StyleSync
//  https://github.com/dylanslewis/StyleSync
//

import UIKit

extension UIColor {

	public static let sampleBlack = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)

	public static let sampleGreen = UIColor(red: 0.159652083392304, green: 0.601748511904762, blue: 0.0407433888268849, alpha: 1.0)

	public static let sampleFire = UIColor(red: 0.872395833333333, green: 0.287587669675442, blue: 0.0456610271826336, alpha: 1.0)

	public static let sampleYellow = UIColor(red: 0.772268282312925, green: 0.724876852462226, blue: 0.129823588099519, alpha: 1.0)

	public static let sampleBrown = UIColor(red: 0.348347151360544, green: 0.207314702727151, blue: 0.082200526306492, alpha: 1.0)

	public static let sampleBlue = UIColor(red: 0.288655698299408, green: 0.564551889896393, blue: 0.886238694190979, alpha: 1.0)

	public static let allGeneratedStylesAndCodeNameAndName: [(UIColor, String, String)] = [
		(.sampleBlack, "sampleBlack", "Sample Black"),
		(.sampleGreen, "sampleGreen", "Sample Green"),
		(.sampleFire, "sampleFire", "Sample Fire"),
		(.sampleYellow, "sampleYellow", "Sample Yellow"),
		(.sampleBrown, "sampleBrown", "Sample Brown"),
		(.sampleBlue, "sampleBlue", "Sample Blue"),
	]
}
