//
//  Automatically generated by SketchStyleExporter
//  https://github.com/dylanslewis/SketchStyleExporter
//

import UIKit

extension UIColor {

	public static let sampleBlack = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)

	public static let sampleGreen = UIColor(red: 0.191107432930772, green: 0.671184098639456, blue: 0.0619833642229185, alpha: 1.0)

	public static let sampleYellow = UIColor(red: 0.970775187015533, green: 0.90723842382431, blue: 0.109462149441242, alpha: 1.0)

	public static let sampleOrange = UIColor(red: 0.968138818027211, green: 0.294141194947221, blue: 0.015318168640661, alpha: 1.0)

	public static let sampleRed = UIColor(red: 0.816203773021698, green: 0.00751322833821177, blue: 0.106696017086506, alpha: 1.0)
}
