//
//  Automatically generated by SketchStyleExporter
//  https://github.com/dylanslewis/SketchStyleExporter
//

import UIKit

extension UIColor {

	public static let sampleBlack = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)

	public static let sampleGreen = UIColor(red: 0.160281344818486, green: 0.658110119047619, blue: 0.0263825710603055, alpha: 1.0)

	public static let sampleYellow = UIColor(red: 0.933328018707483, green: 0.867438621377176, blue: 0.0401223514986506, alpha: 1.0)

	public static let sampleOrange = UIColor(red: 0.968138818027211, green: 0.294141194947221, blue: 0.015318168640661, alpha: 1.0)

	public static let sampleRed = UIColor(red: 0.816203773021698, green: 0.00751322833821177, blue: 0.106696017086506, alpha: 1.0)

	public static let allGeneratedStylesAndCodeNameAndName: [(UIColor, String, String)] = [
		(.sampleBlack, "sampleBlack", "Sample Black"),
		(.sampleGreen, "sampleGreen", "Sample Green"),
		(.sampleYellow, "sampleYellow", "Sample Yellow"),
		(.sampleOrange, "sampleOrange", "Sample Orange"),
		(.sampleRed, "sampleRed", "Sample Red"),
	]
}
